### ISSUE TITLE
TypeError: Cannot read property 'resourceState' saat menjalankan function processImageFromGCSEvent

### ISSUE THREAD

**Issue by abitamaspp** [rhzs/serverless-ktp-ocr#8]
Dear Pak Rheza,

Saya sudah berhasil upload foto KTP ke bucket GCS, tapi function OCR nya ngga jalan. Selalu dapet pesan error begini:
TypeError: Cannot read property 'resourceState' of undefined

Kira-kira kenapa ya?

**Comment by rhzs** [comment]
PR is welcomed. I am bust at this moment or contact me if you need private consultation.
